console.log("Loops in javascript:")

// let a = 1;
// // console.log(a)
// // console.log(a+1)
// // console.log(a+2)

// for (let i = 0; i < 100; i++) {
//     console.log(a + i);
// }


// //for in  loop

// let obj ={
//     name:"Jerry",
//     role:"Programmer",
//     company: "Code with Jerry AI"
// }

// for (const key in obj) {
//     const element = obj[key];

//     console.log(key,element)
    
    
// }

// //for off  loop

// for (const c of "Jerry") {
//     console.log(c)
    
// }

//While  loop

// let i = 0;
// while(i<6000){
//     console.log(i)
//     i++;
// }

//do while  loop

let i = 10;
do {
  console.log(i)
    i++;
} while (i<6);

